channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.0
- pip:
  - mlflow==3.8.1
  - cloudpickle==3.1.2
  - numpy==2.4.1
  - pandas==2.3.3
  - pydot==4.0.1
  - torch==2.9.1
  - torchvision==0.24.1
  - tqdm==4.67.1
name: mlflow-env
